Feature/add ozone class
NOAA-EMC/PyGSI pull request #28
Opened 2021-01-08 18:14 UTC by kevindougherty-noaa

Added Ozone() class to diags.py.

Methods include read_ozone_obs(), get_data(), get_lat_lon(), and analysis_use_idx().

Depending on the type of diagnostic file, returns a dictionary of the total column ozone values and the different layer values. Only filter that can be applied is analysis_use_flag, which determines if the user would like the separated assimilated and monitored data.

2021-01-08 19:20 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                        data_dict[layer] = data
so the dictionary keys are float values + the string 'column_total'? Does that work? Is it ideal?

2021-01-08 19:20 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                        idx = np.where(self.ref_pressure == layer)
like 95% sure that the lat/lon values will be the same for all layers, even total column, so this might be overkill/redundant. How do you do it for the radiances?

2021-01-08 19:20 UTC, aerorahul requested changes
see inline comments.

2021-01-08 19:20 UTC, aerorahul commented on pyGSI/diags.py
> +                lats={}
move these 2 lines before the if-block.

2021-01-08 19:20 UTC, aerorahul commented on pyGSI/diags.py
> +        f.close()
please wrap this in `with open ...` block.

2021-01-08 19:20 UTC, aerorahul commented on pyGSI/diags.py
> +    def get_data(self, dtype, analysis_use=False):
`dtype` is not a good choice here since it is a `numpy` object.

2021-01-08 19:20 UTC, aerorahul commented on pyGSI/diags.py
> +
There are too many `if-else` constructs here, leading to too many repetitive code fragments.

2021-01-08 19:55 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +                        data_dict[layer] = data
Other than that, I'm not too sure what would be best to decipher the different layers and the total column data.

2021-01-08 19:57 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                        data_dict[layer] = data
ok as long as it works, I'm fine with it.

2021-01-08 20:01 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +                        idx = np.where(self.ref_pressure == layer)
You are correct, was overthinking it. However, it is not just as straight forward as Radiance class. It's a combination of the both of them so trying to figure out the best way to do this. I'll work on it and address all comments in another commit.

2021-01-11 21:14 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        if data_type == 'O-F' or data_type == 'o-f':
Can we make these something like (pseudo code) if data_type.ALLCAPS == 'O-F'? Same for below.

2021-01-11 21:14 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        if data_type == 'O-F' or data_type == 'o-f':
I think it's str.upper() or str.lower()? I think lowercase is probably preferred.

2021-01-11 21:14 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +            if self.path.split('/')[-1].split('.')[0].split('_')[2] == 'uv':
if self.variable?

2021-01-11 21:35 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        if data_type == 'O-F' or data_type == 'o-f':
Okay. So if I do `if data_type.lower() == 'o-f'` should I include an "omf" option too?

2021-01-11 21:36 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        if data_type == 'O-F' or data_type == 'o-f':
Maybe:
`if data_type.lower() in ['o-f', 'omf']:
`
?

2021-01-11 21:36 UTC, aerorahul requested changes

2021-01-11 21:36 UTC, aerorahul commented on pyGSI/diags.py
> +        data_type = self.path.split('/')[-1].split('.')[0].split('_')[1]
please use something understandable.
The first split is to get the filename. Use `os.path.basename`.
The second split is to remove the extension. Use `path.without_suffix` from `Pathlib`.
The third split is the one that actually splits the remainder of the string by `_` and get the 2nd item in the list.

2021-01-11 21:36 UTC, aerorahul commented on pyGSI/diags.py
> +        data_type = self.path.split('/')[-1].split('.')[0].split('_')[1]
Why `data_type`.  It is a `diag_type`

2021-01-11 21:36 UTC, aerorahul commented on pyGSI/diags.py
> +            metadata = {'Diag_type': data_type,
Keys don't need to have `_`.
You could name this: `Diagnostic` or `Diag Type`

2021-01-11 21:42 UTC, aerorahul commented on pyGSI/diags.py
> +        if data_type == 'O-F' or data_type == 'o-f':
is `o-f` even a valid choice in the user argument that is passed?

2021-01-11 22:20 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        data_type = self.path.split('/')[-1].split('.')[0].split('_')[1]
Would this be alright?
`import os
from pathlib import Path
os.path.splitext(Path(<file>).stem)[0].split('_')[1]`

Path(<file>).stem grabs file name and removes .nc4.
os.path.splitext( )[0] grabs only the the first part of the filename
.split('_') grabs the item needed, in this case the 2nd item

2021-01-12 13:54 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        if data_type == 'O-F' or data_type == 'o-f':
Yes, however I will add omf/omb and oma if you think that is appropriate and what most users are comfortable with.

2021-01-13 19:06 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        print(str_date)
Remove the print

2021-01-13 19:06 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        diag_type = self.filename.split('_')[1]
diag_type here means something different (conv?) than diag_type below (omb, oma, etc.). Can we have different names? Why is it ftype below the same as diag_type here?

2021-01-13 19:08 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        diag_type = self.filename.split('_')[1]
obs type? perhaps?

2021-01-13 19:08 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +            valid_idx = np.full_like(idxobs, True, diag_type=bool)
this find and replace was dangerous here, might be other places?

2021-01-13 19:14 UTC, aerorahul commented on pyGSI/diags.py
> +        diag_type = self.filename.split('_')[1]
shouldn't this be in the constructor?

2021-01-13 19:15 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        diag_type = self.filename.split('_')[1]
I see now. I believe the find and replace was more harmful than helpful. I'll go through each one and fix. This applies to other comments as well.

2021-01-13 19:16 UTC, aerorahul commented on pyGSI/diags.py
> +        if diag_type.lower() is in ['o-f', 'omf', 'o-b', 'omb']:
I think this was asked earlier, I suggest we stick to `omf` and `oma`, and all lower case.  remove `o-f` and other variants.

2021-01-13 19:16 UTC, aerorahul commented on pyGSI/diags.py
> +        elif diag_type.lower() is in ['o-a', 'omb']:
o-a and omb are different quantities.

2021-01-13 19:17 UTC, aerorahul commented on pyGSI/diags.py
> +        elif diag_type.lower() isin ['h(x)', 'hofx']:
abandon `h(x)` and stick with `hofx`

2021-01-13 19:17 UTC, aerorahul commented on pyGSI/diags.py
> +        elif diag_type.lower() == 'water_fraction':
when you populate `diag_type` make it lower.  Remove `.lower()` from everywhere.

2021-01-13 19:18 UTC, aerorahul commented on pyGSI/diags.py
> +        ftype = self.filename.split('_')[-1]
again, this should be in the constructor.

2021-01-13 19:18 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        diag_type = self.filename.split('_')[1]
So for conventional vs. radiance vs. ozone, what would be a better variable for determining the type it is like in this method? Follow up, what would be better for like the omf, oma etc. I believe my nomenclature is limited and I'm still learning how to better name variables.

2021-01-13 19:45 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        diag_type = self.filename.split('_')[1]
I think ob_type or maybe ob_class works for me, there are 3, conv, rad, oz.

2021-01-13 19:48 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        if diag_type.lower() is in ['o-f', 'omf', 'o-b', 'omb']:
I'm torn on this, on the one hand, I see no harm in having multiple choices, but on the other, it's fine to be consistent and force the users to just use one choice.

2021-01-13 19:48 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        elif diag_type.lower() is in ['o-a', 'omb']:
Yeah this is a typo here I think

2021-01-13 19:49 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        elif diag_type.lower() isin ['h(x)', 'hofx']:
I agree with this one 100%

2021-01-13 19:50 UTC, aerorahul commented on pyGSI/diags.py
> +        if diag_type.lower() is in ['o-f', 'omf', 'o-b', 'omb']:
you can have multiple inputs, but better to redefine once and use that everywhere.

2021-01-13 19:51 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        diag_type = self.filename.split('_')[1]
Okay noted. Would diag_type still be good when referring to the input by the user in terms of omf, oma, observation, etc.?

2021-01-13 19:52 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        ftype = self.filename.split('_')[-1]
Yeah, perhaps instead of ftype, have two booleans, self.anl = True and self.ges = False, and vice versa?

2021-01-13 19:55 UTC, aerorahul commented on pyGSI/diags.py
> +        ftype = self.filename.split('_')[-1]
`is_anl` and `is_ges`
Initialize both to `False` and then set one or the other to `True`.

2021-01-13 19:56 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        if diag_type.lower() is in ['o-f', 'omf', 'o-b', 'omb']:
Perhaps for readability, something like this:
at the very top of the method
```
diag_type = diag_type.lower()
omf = True if diag_type in ['omf', o-f'] else False
oma = True if diag_type in ['oma', o-a'] else False
obs = True if diag_type in ['observation'] else False
hofx = True if diag_type in ['hofx'] else False

```
Then later on:

```
if omf:
  do something

if hofx:
  do something
```

2021-01-13 19:56 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        elif diag_type.lower() is in ['o-a', 'omb']:
It is a typo.

2021-01-13 20:15 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        if diag_type.lower() is in ['o-f', 'omf', 'o-b', 'omb']:
I like this. Should I also add the *_Fraction variables as well and keep it boolean?

2021-01-13 20:18 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        if diag_type.lower() is in ['o-f', 'omf', 'o-b', 'omb']:
yeah make everything boolean I think

2021-01-13 20:52 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        diag_type = self.filename.split('_')[1]
I think so, meaning 'type of diagnostic' to read/grab

2021-01-13 20:58 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        ftype = self.filename.split('_')[-1]
so something like this? 

```
is_anl = False
is_ges = False

if self.ftype == 'ges':
    is_ges = True
else:
    is_anl = True
```

where `self.ftype` is defined in the __init__() constructor. Then I do not need the `check_o_minus_a()` method. and can just do (with doing what Cory mentioned above and making diag_types as boolean):

```
omf = True if diag_type in ['omf', 'o-f', 'omb', 'o-b'] else False

is_anl = False
is_ges = False

if self.ftype == 'ges':
    is_ges = True
else:
    is_anl = True

if omf and is_ges:
    do something
```

2021-01-13 21:01 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        ftype = self.filename.split('_')[-1]
I would do
```
is_ges = True if self.ftype == 'ges' else False
is_anl = True if self.ftype == 'anl' else False
```
that way, in the rare event that it is neither ges nor anl, it doesn't assume anything.

2021-01-13 21:03 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        ftype = self.filename.split('_')[-1]
Got it, less lines of code as well.

2021-01-14 14:44 UTC, aerorahul commented on pyGSI/diags.py
> +                self.omf = f.variables['Obs_Minus_Forecast_adjusted'][:]
This is fine for now, but I would really like to use pandas dataframe here.

2021-01-14 14:44 UTC, aerorahul commented on pyGSI/diags.py
> +                self.omf = f.variables['Obs_Minus_Forecast_adjusted'][:]
or xarray.

2021-01-19 20:05 UTC, CoryMartin-NOAA reviewed
Couple of minor comments still

2021-01-19 20:05 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                diag_type  : type of data to extract i.e. Observation, O-F, O-A, H(x)
Maybe make the defaults here in the string 'observation, omf, Oma, hofx'?

2021-01-19 20:05 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +            self   : GSIdiag object containing the path to extract data
Yeah I think the self : GSIdiag is suggested to be 'GSI ozone diag object' or something similar.

2021-01-19 20:05 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        return "Ozone object"
Maybe say 'ozone GSI diagnostic object' to be explicit?

2021-01-19 22:43 UTC, CoryMartin-NOAA approved these changes
I think I'm happy, will give sometime for @aerorahul to object to anything but I think we've successfully beaten this dead horse

2021-01-19 22:54 UTC, aerorahul commented on pyGSI/diags.py
> +    def read_ozone_obs(self):
name this method read_obs.
and the same in Radiance and Conventional

2021-01-19 22:55 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +    def read_ozone_obs(self):
good catch, agreed. Should be consistent.

2021-01-19 22:56 UTC, aerorahul commented on pyGSI/diags.py
> +    def read_ozone_obs(self):
also, it is private, so it should be `_read_obs`

2021-01-20 01:44 UTC, aerorahul commented on pyGSI/diags.py
>                  u = self.u_omf[idx]
Is this correct?
Shouldn't this be `self.u_oma`

2021-01-20 12:55 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
>                  u = self.u_omf[idx]
Pretty sure this is because of the way the GSI diag files are written. Regardless of if it is loop 1 or 3 (ges/anl), the variable is named 'Observation_minus_forecast', so the part of the code that actually interfaces with netCDF just names the object self.omf. To make it self.oma for oma, we would probably need to add an if/else into the part of the code that reads the variable from the netCDF file.

2021-01-20 14:23 UTC, kevindougherty-noaa commented on pyGSI/diags.py
>                  u = self.u_omf[idx]
Yes, I just double checked and no matter if the file is ges or anl, it is always 'Obs_Minus_Forecast_adjusted'. I can throw a conditional statement just so it is clear to future users.

2021-01-20 14:31 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
>                  u = self.u_omf[idx]
Maybe just make them 'departures'? Or is that too confusing?
```
self.u_dep
self.v_dep
self.dep
```
Then here,
```
if oma and is_anl:
  return self.dep
```
?
I don't feel strongly in any direction but I feel like adding an extra if statement is just making it messier, especially since this is all 'internal' code that the average user won't see.

2021-01-20 14:33 UTC, aerorahul submitted a review, later dismissed

2021-01-20 14:46 UTC, CoryMartin-NOAA approved these changes

2021-01-20 14:47 UTC, merged