Feature/update plotting binning
NOAA-EMC/PyGSI pull request #29
Opened 2021-01-19 19:50 UTC by kevindougherty-noaa

Updated plotting scripts and binning scripts to match variables in diags.py as well as files that create netcdf files

2021-01-20 15:19 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +
These extra lines are the only difference in this file? Can we checkout 'diags.py' from main and not make any changes to it in this PR?

2021-01-20 15:19 UTC, CoryMartin-NOAA commented on pyGSI/netcdf_diags.py
> +        ncfilename = '{Obs Type}_{Variable}_{ObsID[0]}_{Diag Type}.nc'.format(
Rahul will tell you to use f strings haha

2021-01-20 15:19 UTC, CoryMartin-NOAA commented on pyGSI/netcdf_diags.py
> +        metadata['Diag Type'] = 'OmF'
Is there a better way to do this? Do we need all these extra lines and ifs?

2021-01-20 15:19 UTC, CoryMartin-NOAA commented on pyGSI/plot_diags.py
>      else:
Now that we have ozone, need an elif here I think

2021-01-20 15:19 UTC, CoryMartin-NOAA commented on pyGSI/plot_diags.py
>      else:
Or if metadata['Obs Type'] in ['conv', 'oz']

2021-01-20 15:19 UTC, CoryMartin-NOAA commented on pyGSI/plot_diags.py
> +def plot_features(diag_type, stats, metadata):
what exactly are 'features'?

2021-01-20 15:23 UTC, kevindougherty-noaa commented on pyGSI/plot_diags.py
>      else:
Don't all the ozone files come as diag_<sensor>_<satellite>...? Just like the radiance files?

2021-01-20 15:24 UTC, kevindougherty-noaa commented on pyGSI/plot_diags.py
>      else:
that was weird, you cant use '< >'. What I meant was diag_sensor_satellite...

2021-01-20 15:26 UTC, CoryMartin-NOAA commented on pyGSI/plot_diags.py
>      else:
but label is 'brightness temperature', that is what I'm referring to, ozone is a mixing ratio I think (or Dobson units?)

2021-01-20 15:37 UTC, kevindougherty-noaa commented on pyGSI/plot_diags.py
>      else:
oh I see that makes sense now

2021-01-27 18:27 UTC, kevindougherty-noaa commented on pyGSI/netcdf_diags.py
> +        ncfilename = '{Obs Type}_{Variable}_{ObsID[0]}_{Diag Type}.nc'.format(
So the reason I did this rather than fstring is because with f string it would be a lot messier using dictionary values. Would look something like this:

ncfilename = "{metadata['Obs Type']}_{metadata['Variable']}_{metadata['ObsID']} ... etc.

2021-01-27 19:16 UTC, CoryMartin-NOAA requested changes
My main comment is I think there's still some confusion about 'Diag File', which to me suggests the path to the netCDF file, and I think it should be more like 'Obs Type', for conventional, radiance, or ozone. Then places where Obs Type are used (ozone only?) you need sensor and satellite together, and for conventional you use variable, ObsID and subID (or whatever they're called) to indicate radiosondes, surface, etc.

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        self.metadata['Diag File'] = 'conventional'
Still sorta confused on this, should this be 'Diag File'? That suggests to me the path/filename. I would suggest 'Diag Type' but I see that is defined below...

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        self.metadata['Diag Type'] = diag_type
is diag_type here 'conventional' or 'temperature'? If the Former, is 'temperature' defined anywhere?

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        self.metadata['Diag File'] = 'radiance'
Same comment as above.

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        self.metadata['Diag Type'] = diag_type
Again, what is type here, radiance, or satellite/sensor?

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        self.metadata['Diag File'] = 'ozone'
Same again.

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        self.metadata['Diag Type'] = diag_type
x3

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/netcdf_diags.py
> +    if obs_type == 'conv':
ok so I like 'obs_type' here, can we be consistent in the other file with this one?

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/netcdf_diags.py
> +    if metadata['Diag File'] == 'conventional':
I think this needs to be 'Obs Type', which I think answers my above questions. You use 'Obs Type' below in the string.

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/netcdf_diags.py
> +        ncfilename = '{Obs Type}_{Variable}_{ObsID[0]}_{Diag Type}.nc'.format(
Does 'Obs Type' work in this context? Did you test this? Is it fine because you pass it a full dict?

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/netcdf_diags.py
> +        ncpath = metadata['Outdir']+'/'+ncfilename
if the rest of the metadata keys are now spaced names, why not 'Output Dir'? or something similar?

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/netcdf_diags.py
> +        if metadata['Diag File'] == 'conventional':
Same comment/concerns as before.

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/plot_diags.py
> +# Updated January 2021
No need to do this because GitHub will keep the record of when things are changed.

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/plot_diags.py
> +    elif metadata['Diag File'] == 'conventional':
Flagging for awareness, think this should be fixed or at least discussed.

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/plot_diags.py
> +        roundnum = 6
is this the number of digits to round to? Is there a better name than 'roundnum'? I guess it's probably okay

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/plot_diags.py
> +        if metadata['Diag File'] == 'conventional':
here's another spot.

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on pyGSI/plot_diags.py
> +        save_file = '{Date:%Y%m%d%H}_{Obs Type}_{Satellite}_{Diag Type}_{Diag File}'.format(
I don't think we need the filename for the figure to end in ozone, it will be implied by ompslp...blah blah whatever for obs type and satellite, which should be 'sensor' and 'satellite'

2021-01-27 19:16 UTC, CoryMartin-NOAA commented on scripts/create_conv_netcdf.py
>      diagfile = conv_config['conventional input']['path'][0]
see this proves my point about the confusion of the name of the key in the dictionary above

2021-01-27 19:27 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        self.metadata['Diag File'] = 'conventional'
So my main motivation for this is because I needed to separate by diagnostic file type conventional, ozone, or radiance. I cannot get this information straight from the file other than conventional where 'Obs Type' from the file name would be 'conv'. However, this gets complicated with radiance and ozone because 'Obs Type' from the filename is the sensor name. I would then have to distinguish all the different sensors and satellites between radiance and ozone.

2021-01-27 19:29 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        self.metadata['Diag Type'] = diag_type
'Diag Type' is omf, observation, hofx, etc. 'Variable' would be like temperature, q, uv etc.

2021-01-27 19:32 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        self.metadata['Diag File'] = 'conventional'
I get the reason for this, but Diag File isn't the right label/name is what I'm saying. What about self.metadata['conventional'] = True? and self.metadata['radiance'] = False and self.metadata['ozone'] = False?

2021-01-27 19:39 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        self.metadata['Diag File'] = 'conventional'
Yes I can do that, but will need to make sure to include all 3 in every instance otherwise will need to add a similar line like when Anl Use is added: `anl_use = True if 'Anl Use' in metadata else False`

2021-01-27 19:41 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        self.metadata['Diag File'] = 'conventional'
yeah that's probably more work than is needed. What about just 'Diag File Type'? Just so it's clearer

2021-01-27 19:41 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +        self.metadata['Diag File'] = 'conventional'
or just 'File Type'

2021-01-27 19:44 UTC, kevindougherty-noaa commented on pyGSI/diags.py
> +        self.metadata['Diag File'] = 'conventional'
So File Type is already taken because that is either 'ges' or 'anl' from the filename. So 'Diag File Type' works with me. I understand the confusion, there's a lot of different variable names that are in play here.

2021-01-28 15:35 UTC, CoryMartin-NOAA commented
@kevindougherty-noaa do we think every comment has been addressed and it's ready to merge? I think so, but I want to double check with you.

2021-01-28 15:48 UTC, kevindougherty-noaa commented
@CoryMartin-NOAA Yes, the comments have been addressed and I believe it is ready to be merged. Let me change the shell scripts to be up to date with new changes and it will be ready to be added.

2021-01-28 17:26 UTC, CoryMartin-NOAA approved these changes

2021-01-28 17:43 UTC, merged