PyGSI issue #56, add binning by height to class Conventional.
NOAA-EMC/PyGSI pull request #57
Opened 2021-07-22 18:53 UTC by EdwardSafford-NOAA

Modified class conventional to bin data by height instead of pressure.   The default (assuming binning is used) is pressure.  I'm working on adding vertical plots for gps data to the package and height (altitude) makes much more sense for gps data than does pressure.  This extension is a prerequisite for those plots.

I've run scripts/batch_conv_diags.sh both with the original code and with my changes and the results are identical.

2021-07-26 13:46 UTC, CoryMartin-NOAA requested changes

2021-07-26 13:46 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +            self.height = f.variables['Height'][:]/1000  	# convert height from meters to km
Why convert from meters to km? Is this just for plotting? If so, suggest converting it later.

2021-07-26 13:46 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                lvl_type     : lvls definition as 'pressure' or 'height'.  Default is 'pressure'.
this says default is 'pressure' but lvl_type default is `None`. Suggest changing the function definition so that lvl_type='pressure'

2021-07-26 13:46 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +    def get_lat_lon(self, obsid=None, subtype=None, station_id=None, analysis_use=False, lvls=None, lvl_type=None):
Same comments as above about default lvl_type.

2021-07-26 13:46 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                    binned_lats[pressure] = self.lats[pidx]
shouldn't this be `binned_lats[low_bound]`?

2021-07-27 16:35 UTC, EdwardSafford-NOAA commented on pyGSI/diags.py
> +            self.height = f.variables['Height'][:]/1000  	# convert height from meters to km
Yes, it's just for plotting.  Will remove the conversion and implement it in the new vertical plotting routine.

2021-07-27 17:28 UTC, EdwardSafford-NOAA commented on pyGSI/diags.py
> +                lvl_type     : lvls definition as 'pressure' or 'height'.  Default is 'pressure'.
Will do.

2021-07-27 17:28 UTC, EdwardSafford-NOAA commented on pyGSI/diags.py
> +                    print( "WARNING:  input lvl_type ', lvl_type, ' does not match expected values of height or pressure" )
Will do.

2021-07-27 17:28 UTC, EdwardSafford-NOAA commented on pyGSI/diags.py
> +    def get_lat_lon(self, obsid=None, subtype=None, station_id=None, analysis_use=False, lvls=None, lvl_type=None):
Will do.

2021-07-27 17:28 UTC, EdwardSafford-NOAA commented on pyGSI/diags.py
> +                    binned_lats[pressure] = self.lats[pidx]
Indeed.  Good catch.

2021-07-30 14:29 UTC, EdwardSafford-NOAA reviewed
I believe I've made all the requested changes.  I managed though to some how mess up the amended commit and so foiled my squash merge.  In cases like this with the GSI repo, I've been asked to cancel the PR and re-do the squash merge.  If you'd like me to do that here I'll make it so.

2021-07-30 14:32 UTC, CoryMartin-NOAA commented
@EdwardSafford-NOAA I don't quite understand why we have to do it with GSI, as I can just do a squash merge on GitHub once everything is approved. Let me do another quick review here now.

2021-07-30 14:36 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                raise ValueError('{lvl_type} wrong, use "pressure" or "height" for input lvl_type'.format(lvl_type=repr(lvl_type)))
This is fine and doesn't need to be changed, because I doubt we will have more than pressure or height, but you can do something like:
`raise ValueError(f'{lvl_type} wrong. Valid choices are: {" | ".join(_VALID_LVL_TYPES)}')`

2021-07-30 14:36 UTC, EdwardSafford-NOAA commented
Sorry my wording was vague.  I meant when working with the GSI package it was handled as I described, but I wasn't sure canceling and opening a new PR was the preferred method within the PyGSI package.

2021-07-30 14:38 UTC, CoryMartin-NOAA approved these changes

2021-07-30 14:38 UTC, merged

2021-07-30 14:39 UTC, CoryMartin-NOAA commented
Looks good @EdwardSafford-NOAA , thanks for adding this!

2021-07-30 14:41 UTC, EdwardSafford-NOAA commented on pyGSI/diags.py
> +                raise ValueError('{lvl_type} wrong, use "pressure" or "height" for input lvl_type'.format(lvl_type=repr(lvl_type)))
Good idea.  I'll add that with my next set of changes.