Modified diags.py,adding more read observatio items, the data categor…
NOAA-EMC/PyGSI pull request #60
Opened 2021-09-02 18:44 UTC by XiujuanSu-NOAA

See the reference  to issue  #59  and  #81460

2021-09-02 18:57 UTC, CoryMartin-NOAA requested changes
One very minor change, otherwise I think it looks good

2021-09-02 18:57 UTC, CoryMartin-NOAA commented on pyGSI/diags.py
> +                        rejected_idx[0], pres_idx[0])
Can you fix the indentation of this line so that it matches the others?

2021-09-02 19:11 UTC, EdwardSafford-NOAA submitted a review, later dismissed
Looks good.

2021-09-02 19:18 UTC, XiujuanSu-NOAA commented
Sure Thanks

Su

On Thu, Sep 2, 2021 at 2:57 PM Cory Martin ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> One very minor change, otherwise I think it looks good
> ------------------------------
>
> In pyGSI/diags.py
> <https://github.com/NOAA-EMC/PyGSI/pull/60#discussion_r701344053>:
>
> >                         valid_monitored_idx = np.isin(
>                             monitored_idx[0], hght_idx[0])
>                      else:
>                         pres_idx = np.where((self.press > level_list[i]) & (
>                             self.press <= level_list[i+1]))
>                         valid_assimilated_idx = np.isin(
>                             assimilated_idx[0], pres_idx[0])
> +                       valid_rejected_idx = np.isin(
> +                        rejected_idx[0], pres_idx[0])
>
> Can you fix the indentation of this line so that it matches the others?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/PyGSI/pull/60#pullrequestreview-745414840>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP5S7HSITCPXGEWVEDSDX7LT77CKPANCNFSM5DJXIIWQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-03 15:15 UTC, CoryMartin-NOAA approved these changes

2021-09-03 15:16 UTC, merged